#!/bin/sh

alias zshrc="vim ~/.config/zsh"
alias zshrcs="source ~/.config/.zshrc"
alias vim=lvim
alias ll="exa -l -g --icons"
alias ls="exa --icons"
alias lt="exa --tree --icons -a -I '.git|__pycache__|.mypy_cache|.ipynb_checkpoints'"
alias termfast="sudo rm -f /private/var/log/asl/*.asl"
alias config='/usr/bin/git --git-dir=/Users/tanhopdo/.cfg/ --work-tree=/Users/tanhopdo'
# show file previews for fzf using bat
alias fp="fzf --preview 'bat --style=numbers --color=always --line-range :500 {}'"
alias ide="
#!/bin/bash
tmux split-window -v -p 30
tmux split-window -h -p 66
tmux split-window -h -p 50
tmux select-pane -U
"
alias ide2="
#!/bin/bash
tmux split-window -v -p 30
tmux split-window -h
tmux select-pane -U
"
alias ide3="
#!/bin/bash
tmux split-window -h -p 25 
tmux split-window -v
tmux select-pane -L
"

alias f='zi'
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac
